from keras.models import load_model  # TensorFlow is required for Keras to work
from PIL import Image, ImageOps  # Install pillow instead of PIL
import numpy as np
def get_class(model_path, labels_path, image_path):
    np.set_printoptions(suppress=True)

    model = load_model(model_path, compile=False)

    class_names = open(labels_path, "r", encoding="utf-8").readlines()

    data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
    
    image = Image.open(image_path).convert("RGB")
    size = (224, 224)

    image = ImageOps.fit(image, size, Image.Resampling.LANCZOS)
    image_array = np.asarray(image)
    normalized_image_array = (image_array.astype(np.float32) / 127.5) - 1

    data[0] = normalized_image_array

    prediction = model.predict(data)

    index = np.argmax(prediction)

    class_name = class_names[index]

    confidence_score = prediction[0][index]
    
    if class_name[2:] == 'Albert Einstein\n':
        ilmuan = 'Albert Einstein adalah fisikawan teoretis kelahiran Jerman yang dianggap sebagai salah satu ilmuwan terbesar sepanjang masa. Ia terkenal karena teori relativitas dan kontribusinya dalam mekanika kuantum, dua pilar fisika modern. Persamaan terkenalnya, \( E = mc^2 \), dikenal sebagai “persamaan paling terkenal di dunia. Pada tahun 1921, Einstein menerima Nobel Fisika atas penemuannya tentang hukum efek fotolistrik, yang berperan penting dalam perkembangan teori kuantum. Pada awal kariernya, Einstein menemukan bahwa mekanika Newton tidak bisa menyatukan hukum klasik dengan medan elektromagnetik, yang mendorongnya mengembangkan teori relativitas khusus. Teori ini lalu diperluas menjadi teori relativitas umum, yang menjelaskan gravitasi. Einstein juga menyumbangkan konsep penting di bidang teori partikel, gerak molekul, dan termal cahaya. Setelah menempuh pendidikan di Swiss dan bekerja di Eropa, Einstein menetap di Amerika Serikat pada 1933 saat Nazi berkuasa di Jerman. Ia menjadi warga negara Amerika pada tahun 1940. Menjelang Perang Dunia II, ia memperingatkan Presiden Roosevelt tentang potensi bom atom, yang akhirnya memicu Proyek Manhattan. Meski mendukung Sekutu, Einstein menentang penggunaan senjata nuklir. Einstein menerbitkan lebih dari 300 makalah ilmiah dan 150 karya lainnya. Hingga akhir hayatnya, ia bekerja di Institute for Advanced Study di Princeton. Namanya kini identik dengan kecerdasan dan “genius.” Einstein menerima banyak penghargaan, termasuk Nobel Fisika 1921, yang diberikan pada tahun 1922 "atas jasanya terhadap Fisika Teoretis, terutama atas penemuan hukum efek fotolistrik." Nobel tahun 1921 ini diberikan kepadanya karena tidak ada kandidat lain yang memenuhi kriteria penghargaan tersebut.'
    elif class_name[2:] == 'Isaac Newton\n':
        ilmuan = 'Sir Isaac Newton adalah fisikawan, matematikawan, dan ilmuwan Inggris yang diakui sebagai salah satu tokoh paling berpengaruh dalam sejarah sains. Bukunya, *Philosophiæ Naturalis Principia Mathematica* (1687), meletakkan dasar mekanika klasik, menjelaskan hukum gravitasi, dan tiga hukum gerak yang menjadi panduan ilmiah selama tiga abad. Newton menunjukkan bahwa hukum alam berlaku sama untuk benda di Bumi dan di luar angkasa, memperkuat teori heliosentrisme. Dalam optika, Newton menciptakan teleskop pemantul pertama dan mengembangkan teori warna melalui prisma. Di matematika, ia bersama Gottfried Leibniz mengembangkan kalkulus, serta menciptakan "metode Newton" dan teori binomial. Hingga kini, Newton tetap sangat berpengaruh, bahkan dalam survei tahun 2005 oleh Royal Society, ia dinilai memberikan kontribusi sains lebih besar daripada Einstein.'
    elif class_name[2:] == 'Marie Curie\n':
        ilmuan = 'Marie Curie adalah pelopor di bidang radiologi dan peraih dua Hadiah Nobel, dalam Fisika (1903) dan Kimia (1911). Bersama suaminya, Pierre Curie, ia menemukan unsur radium dan mendirikan Institut Curie. Curie adalah wanita pertama yang meraih Nobel dan orang pertama yang memenangkan dua Nobel dalam dua bidang berbeda. Marie dibesarkan di Polandia dalam keluarga guru. Meski miskin dan harus belajar secara sembunyi-sembunyi, ia akhirnya melanjutkan studi fisika dan matematika di Universitas Sorbonne, Paris. Di sana, ia berhasil mengisolasi radium, yang menjadi dasar ketenarannya dalam dunia ilmiah. Marie Curie bersama suaminya dan Henri Becquerel memenangkan Hadiah Nobel Fisika pada 1903 untuk penelitian tentang radioaktivitas, yang membawanya ke pengakuan internasional dan memungkinkan mereka melanjutkan penelitian.'
    elif class_name[2:] == 'Julius Robert Oppenheimer\n':
        ilmuan = 'Julius Robert Oppenheimer adalah fisikawan teoretis Amerika yang memimpin Laboratorium Los Alamos selama Perang Dunia II dan dikenal sebagai "bapak bom atom" karena perannya dalam Proyek Manhattan, yang menciptakan senjata nuklir pertama. Ia lahir di New York dari keluarga Yahudi-Jerman, belajar kimia di Harvard, dan menyelesaikan doktor di bidang fisika di Jerman pada 1927. Setelah berkontribusi dalam fisika teori, Oppenheimer menjadi kepala proyek bom atom di Los Alamos pada 1943. Ia menyaksikan uji coba bom pertama, Trinity, pada 1945, dan senjata itu kemudian digunakan di Hiroshima dan Nagasaki. Usai perang, ia menjadi direktur di Institute for Advanced Study, menyarankan pengawasan nuklir internasional, dan menentang pengembangan bom hidrogen. Pada 1954, selama era McCarthyisme, izin keamanannya dicabut karena tuduhan keterkaitannya dengan Partai Komunis, yang mengakhiri kariernya di fisika nuklir. Namun, pada 1963 ia dianugerahi Penghargaan Enrico Fermi, dan pada 2022, pemerintah AS membatalkan pencabutan izin keamanannya karena prosesnya dinilai tidak adil. Pada September 1957, Oppenheimer menerima penghargaan Légion dhonneur dari Prancis dan pada Mei 1962, ia terpilih sebagai anggota Royal Society Inggris. Pada 1963, atas desakan teman-temannya, Presiden Kennedy menganugerahinya Penghargaan Enrico Fermi untuk memulihkan status politiknya. Setelah pembunuhan Kennedy, Presiden Lyndon B. Johnson menyerahkan penghargaan ini kepadanya, mengakui kontribusinya dalam fisika dan kepemimpinannya di Laboratorium Los Alamos. Penghargaan itu bersifat simbolis, karena Oppenheimer tetap tak memiliki izin keamanan dan peran dalam kebijakan resmi, tetapi ia menerima uang bebas pajak sebesar $50.000. Penghargaan ini menimbulkan kontroversi di Kongres, dan beberapa anggota Partai Republik memboikot acara pemberian penghargaan.'
    elif class_name[2:] == 'Ibnu Sina\n':
        ilmuan = 'Ibnu Sina, dikenal di Barat sebagai Avicenna, adalah seorang cendekiawan Muslim dari Zaman Keemasan Islam yang dianggap sebagai salah satu dokter dan filsuf paling berpengaruh di era pra-modern. Ia dijuluki "Bapak Kedokteran Modern" dan menulis sekitar 450 karya, dengan 240 di antaranya masih bertahan, termasuk 40 karya medis dan 240 karya filsafat. Karyanya yang paling terkenal adalah *Al-Qānūn fī al-Thibb* (Buku Pengobatan), yang menjadi acuan standar dalam dunia kedokteran selama berabad-abad. Ibnu Sina lahir pada tahun 980 di dekat Bukhara (sekarang Uzbekistan) dan wafat pada 1037 di Hamadan, Persia (sekarang Iran).'
    elif class_name[2:] == 'Nikola Tesla\n':
        ilmuan = 'Nikola Tesla (10 Juli 1856 7 Januari 1943) adalah penemu, insinyur, dan futuris Serbia-Amerika yang terkenal atas kontribusinya pada sistem listrik arus bolak-balik (AC). Lahir di Kekaisaran Austria (sekarang Kroasia), Tesla belajar teknik dan fisika, tetapi tidak menyelesaikan gelarnya. Ia bekerja di bidang listrik dan telekomunikasi di Eropa sebelum pindah ke Amerika Serikat pada 1884, di mana ia menjadi warga negara. Tesla sempat bekerja di Edison Machine Works sebelum mendirikan laboratorium sendiri untuk mengembangkan berbagai penemuan. Salah satu inovasinya yang penting adalah motor induksi AC, yang menjadi dasar sistem listrik modern. Tesla juga bereksperimen dengan teknologi seperti pencahayaan nirkabel, daya frekuensi tinggi, pencitraan sinar-X, dan perahu yang dikendalikan jarak jauh. Ia dikenal sebagai penemu yang karismatik dan sering melakukan demonstrasi publik. Proyek ambisiusnya, seperti Menara Wardenclyffe untuk komunikasi dan distribusi daya nirkabel, gagal karena kekurangan dana. Setelah mengalami kesulitan keuangan, Tesla meninggal dalam kesendirian di New York pada 1943. Namanya diabadikan dalam satuan magnetik "tesla" pada 1960, dan minat terhadap karya-karyanya kembali meningkat sejak 1990-an.'
    elif class_name[2:] == 'Galileo Galilei\n':
        ilmuan = 'Galileo Galilei (15 Februari 1564 8 Januari 1642) adalah seorang astronom, filsuf, dan fisikawan Italia yang berperan besar dalam revolusi ilmiah. Ia dijuluki "bapak ilmu pengetahuan modern" karena kontribusinya, termasuk penyempurnaan teleskop, pengamatan astronomi, hukum gerak, dan dukungannya terhadap teori heliosentris Copernicus yang menyatakan bahwa matahari adalah pusat tata surya. Pandangan Galileo tentang heliosentrisme bertentangan dengan keyakinan Gereja Katolik dan ajaran Aristoteles yang menyatakan bumi sebagai pusat alam semesta. Akibatnya, ia diadili oleh pengadilan gereja pada 1633 dan dijatuhi hukuman tahanan rumah hingga meninggal. Pada 1992, Gereja Katolik mengakui kesalahan penghukumannya, dan pada 2008, namanya direhabilitasi sebagai ilmuwan. Menurut Stephen Hawking, Galileo adalah salah satu tokoh terpenting dalam sejarah sains modern. Konfliknya dengan Gereja menjadi simbol awal perjuangan kebebasan berpikir dalam ilmu pengetahuan melawan otoritas agama.'
    elif class_name[2:] == 'B.J.Habibie\n':
        ilmuan = 'Bacharuddin Jusuf Habibie (25 Juni 1936 11 September 2019) adalah Presiden Indonesia ketiga yang menjabat dari 21 Mei 1998 hingga 20 Oktober 1999, menggantikan Soeharto yang mundur di tengah krisis reformasi. Sebelumnya, ia menjadi Wakil Presiden Indonesia ketujuh menggantikan Try Sutrisno. Habibie adalah teknokrat dan ilmuwan teknologi penerbangan internasional, serta satu-satunya presiden Indonesia dengan latar belakang ilmiah. Habibie, yang berasal dari Parepare, Sulawesi Selatan, adalah presiden Indonesia pertama yang lahir di luar Jawa. Ia memiliki keturunan Bugis-Gorontalo dari ayahnya dan Jawa dari ibunya. Masa jabatannya sebagai Wakil Presiden (2 bulan 7 hari) dan Presiden (1 tahun 5 bulan) merupakan yang terpendek dalam sejarah Indonesia. Ia digantikan oleh Abdurrahman Wahid (Gus Dur) setelah Pemilu 1999. Selain sebagai politisi, Habibie menghasilkan banyak karya di bidang aeronautika dan teknologi, termasuk penelitian ilmiah dan publikasi internasional. Buku-buku terkenalnya adalah *Detik-detik yang Menentukan* (2006), yang membahas perannya dalam reformasi, serta *Habibie dan Ainun* (2009), memoar tentang kisah cintanya. Habibie juga berperan dalam pengembangan pesawat N-250 Gatotkaca.'

    return(ilmuan)